### ISSUE TITLE
Das ° kann zu Problemen führen

### ISSUE THREAD

**Issue by MaStr** [juergen-rocks/raumklima#2]
https://github.com/juergen-rocks/raumklima/blob/5099980089ab9a957223344b2ef73fd1e7c49c73/src/read_rs500.py#L15

Das Grad-Zeichen ist leider nicht ganz ideal. Mein C.H.I.P. (mit prop. Armbian) läuft im default leider als ASCII und daher versucht Python das irgendwie zu interpretieren:

````
$ python3 read_rs500.py
--------------------------------
Channel | Temperature | Humidity
================================
Traceback (most recent call last):
  File "read_rs500.py", line 21, in <module>
    get_and_print()
  File "read_rs500.py", line 16, in get_and_print
    print('{:7d}  \xb0'.format(i))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 9: ordinal not in range(128)
````
Unglücklicherweise hat der Nano und vi das Zeichen auch noch ausgeblendet... somit bin ich nur schwer auf den Fehler gestoßen :-(

Eventuell ausbauen? Es ist ja letztlich nur eine Debug-Hilfe...

**Comment by edelbluth** [comment]
Dieses ganze Skript ist nur eine einfache Möglichkeit, die Daten auszulesen.

Hier werde ich das Grad-Symbol nicht heraus nehmen. 

Dennoch vielen Dank für diesen Hinweis. Möglicherweise hilft er jemand anderem, der auf das gleiche Problem stößt.
