### ISSUE TITLE
ELV Klimastation nun unter eigenem Label dnt

### ISSUE THREAD

**Issue by MaStr** [juergen-rocks/raumklima#40]
Moin,

zur Info, die Klimastation wird neuerdings unter dem ELV Brandt "dnt" vertrieben:

https://de.elv.com/dnt-spar-set-funk-raumklimastation-roomlogg-pro-mit-8-thermo-hygrosensoren-und-auswertesoftware-251349?fs=2684770435

Ich tippe stark darauf, dass das das gleiche Gerät ist.. aber kann es mangels Hardware nicht probieren.

(Wollte es nur mal dokumentiert haben).

Lg Matthias

**Comment by edelbluth** [comment]
Sieht tatsächlich sehr sehr ähnlich aus... Möglicherweise hat sich vielleicht noch die Device-ID oder die Vendor-ID geändert. Aber das wird es schon gewesen sein.

**Comment by devdev-dev** [comment]
Ich hab das Gerät unter dem Namen dnt. Kann ich euch Infos dazu liefern?
Hier mal die Device Information: ![MVIMG_20200818_194736](https://user-images.githubusercontent.com/1813071/90547615-19a2eb80-e18c-11ea-9803-7c0f257d76f7.jpg)
- Hardware Version: 1.1.0
- Firmware Version 1.2.4
- Bootloader Version 1.1.2

**Comment by edelbluth** [comment]
@devdev-dev: Gibt es die Möglichkeit, das Gerät mal an einen Linux-Rechner anzuschließen und mal mit `dmesg` zu schauen, wie das Gerät erkannt wird? Sollte dann so ähnlich aussehen, wie hier:

```
usb 1-1.3: new full-speed USB device number 5 using dwc_otg
usb 1-1.3: New USB device found, idVendor=0483, idProduct=5750
usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 1-1.3: Product: By viewtool
usb 1-1.3: Manufacturer: MyUSB_HID
usb 1-1.3: SerialNumber: ************
hid-generic 0003:0483:5750.0005: hiddev0,hidraw0: USB HID v1.10 Device [MyUSB_HID By viewtool] on usb-20980000.usb-1.3/input0
```

(siehe auch [https://juergen.rocks/blog/articles/elv-raumklimastation-rs500-raspberry-pi-linux.html#geht-da-nicht-vielleicht-doch-was-mit-linux](https://juergen.rocks/blog/articles/elv-raumklimastation-rs500-raspberry-pi-linux.html#geht-da-nicht-vielleicht-doch-was-mit-linux))

Besonders interessant sind die Vendor-ID und die Product-ID (`usb 1-1.3: New USB device found, idVendor=0483, idProduct=5750`). Wenn die noch passen, dann sollten wir mal probieren, ob das Auslesen schon "von Haus aus" klappt. Passen die IDs nicht, stelle ich Dir gerne eine geänderte Version zum Probieren zur Verfügung und überlege mir gerne, wie wir Product- und Vendor-ID konfigurierbar machen (was eigentlich kein Thema sein sollte).

Vielen Dank für Deine Unterstützung!

**Comment by devdev-dev** [comment]
Ich schau was sich machen lässt und erstelle mir mal einen bootbaren Linux Stick um es auszulesen.

**Comment by ca-haddock** [comment]
HI

die dnt ist baugleich das auslesen mir der software funktioniert ohne Änderungen.

./read_rs500.py
--------------------------------
Channel | Temperature | Humidity
================================
      1 |     22.9 °C |     52 %
      2 |     23.3 °C |     51 %
 .....

habe 8 sensoren die prima funktionierten.

**Comment by ca-haddock** [comment]
HI

die dnt ist baugleich das auslesen mir der software funktioniert ohne Änderungen.
habe 8 sensoren die prima Funktionierten.

**Comment by edelbluth** [comment]
@ca-haddock Vielen Dank!

**Comment by edelbluth** [comment]
Aufgabe an mich selbst: Dokumentieren, dass es auch mit der dnt-Station funktioniert.

**Comment by edelbluth** [comment]
Blog-Post kommt dann noch bei Gelegenheit 😺

**Comment by klofrau** [comment]
> Ich hab das Gerät unter dem Namen dnt. Kann ich euch Infos dazu liefern? Hier mal die Device Information: ![MVIMG_20200818_194736](https://user-images.githubusercontent.com/1813071/90547615-19a2eb80-e18c-11ea-9803-7c0f257d76f7.jpg)
> 
>     * Hardware Version: 1.1.0
> 
>     * Firmware Version 1.2.4
> 
>     * Bootloader Version 1.1.2

@devdev-dev Kannst du mir sagen wie die SD-Karte formatiert sein muss? ext4 und exfat waren nicht erfolgreich. Auf deinem Bild erkenne ich, dass die Karte erfolgreich erkannt wird. Frage mich mit welchem Dateisystem

**Comment by MaStr** [comment]
Versuche es bitte mal mit vfat.

**Comment by klofrau** [comment]
@MaStr Danke, das war es. Firmwareupdate lief dann sofort durch.
