### ISSUE TITLE
Kontakt zum Hersteller

### ISSUE THREAD

**Issue by devdev-dev** [juergen-rocks/raumklima#45]
Gab es denn bisher Versuche den Hersteller mal direkt nach dem Source Code zu fragen?

**Comment by edelbluth** [comment]
Ich hatte damals bei ELV gefragt, ob es da irgend eine Unterstützung gibt, zumindest, um das "mitgesniffte" Protokoll zu bestätigen.

Die Antwort war "Nein, das Gerät wird nur und ausschließlich von Windows unterstützt".

**Comment by devdev-dev** [comment]
Mal abgesehen vom USB-Protokoll wäre es toll gewesen Anpassungen an der Monitor-Software selbst vorzunehmen. Konkret würde ich gerne die Channelbezeichnungen anpassen um einen Hinweis auf den Raum zu geben.

Sehr schade, dass viele Firmen immer noch ihre Geschäft durch agile und offene Arbeit gefährdet sehen. Danke für die Antwort 👍
