### ISSUE TITLE
Fehler beim MQTT beim Verlust der MQBroker Verbindung

### ISSUE THREAD

**Issue by MaStr** [juergen-rocks/raumklima#47]
Hi,
nur um den Fehler erstmal zu Dokumentieren.. ich versuche mich selbst dem Thema noch widmen. 

Wenn der MQBroker plötzlich "weg" ist, ist es bei mir zu hängenden Sessions gekommen, die dann -bedingt durch die hohe Frequenz des cronjobs - das System fast an die Wand gefahren hat wegen out of memory.

Ich muss mir im Detail mal genau das anschauen was passiert wenn die Verbindung nicht aufgebaut werden kann, aber es darf unter keinen Umständen dazu kommen, dass das Skript eine "unendlich" lange Zeit mit dem Verbindungsaufbau verbringt.

liebe Grüße
Matthias

**Comment by edelbluth** [comment]
Alles klar. Die MQTT-Anbindung liegt ja immer noch im `develop`-Branch, weil ich noch nicht dazu gekommen bin, mir ein paar sinnvolle Tests auszudenken und daher noch kein Release gebaut habe.

**Comment by MaStr** [comment]
Ich habe das heute Morgen mal getestet. Der MQTT Client geht mit einem Default-Timeout von 60s raus.
Der Redis-Client scheint die Ursache zu sein, denn der geht erst nach 129s raus:

```
$ time ./check_rs500.py -c 1
unknown: Redis error

real	2m9.755s
user	0m0.069s
sys	0m0.004s

```
Den Connect Timeout für MQTT habe ich eingebaut. Ich mache das gleich noch für Redis.

**Comment by edelbluth** [comment]
Durch #50 erledigt, danke!
