### ISSUE TITLE
open failed

### ISSUE THREAD

**Issue by tfMovamo** [juergen-rocks/raumklima#5]
```
(venv) pi@raspb-trans:~/raumklima/src $ ./start_save_rs500_to_redis.sh
open failed
Traceback (most recent call last):
  File "./save_rs500_to_redis.py", line 23, in <module>
    fetch_and_save()
  File "./save_rs500_to_redis.py", line 12, in fetch_and_save
    data = reader.get_data()
  File "/home/pi/raumklima/src/rs500reader/reader.py", line 40, in get_data
    if len(data) != 64:
TypeError: object of type 'NoneType' has no len()
```

Ein `print(data)` ergibt "None" bei mir.
Dadurch wird unter anderem die Exception nicht geworfen.
Müsste ersetzt werden durch: `if data == None or len(data) != 64:`

Dann wird jedoch obige Meldung ausgespuckt.
Haben sie da vielleicht eine Idee??

**Comment by edelbluth** [comment]
Auf den ersten Blick schlägt hier das Thema aus #4 auf - denn in der Standard-Konfiguration benötigt das Leseskript Root-Rechte, um auf die Hardware zugreifen zu können. Das habe ich bisher (trotz der guten Idee aus #4) noch nicht behoben.

@tfMovamo: Bitte mal den Aufruf mit `sudo ./start_save_rs500_to_redis.sh` versuchen.

Das ändert jedoch nichts daran, dass die Fehlerbehandlung an dieser Stelle alles andere als optimal ist. Insofern behandele ich das als Bug und sorge für eine aussagekräftigere Fehlermeldung in diesem Falle.

**Comment by edelbluth** [comment]
4 Wochen ohne Antwort. _No news are good news._

Dennoch vielen Dank!

**Comment by tfMovamo** [comment]
Oh, sorry.
die Mails sind im Spam gelandet....

Mit root rechten läuft es. Danke
